#!/usr/bin/env bash
#/bin/bash
case "$1" in
  "list")
    CRD=$2
    for i in $(kubectl get crd | grep ${CRD} | awk '{print $1}'); do echo $i; kubectl get $i --all-namespaces; done
    ;;
  "delete")
    CRD=$2
    for ns in $(kubectl get ns | grep Active | awk '{print $1}'); do for i in $(kubectl get crd | grep ${CRD} | awk '{print $1}'); do kubectl delete --all $i -n $ns; done; done
    ;;
  "get")
    TYPE=$2
    NAMESPACE=$3
    NAME=$4
    kubectl get $TYPE -n $NAMESPACE $NAME -o yaml
    ;;
  *)
    echo "You have failed to specify what to do correctly."
    exit 1
    ;;
esac
