// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: install.proto

package v1 // import "github.com/solo-io/supergloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// @solo-kit:resource.short_name=install
// @solo-kit:resource.plural_name=installs
// @solo-kit:resource.resource_groups=install.supergloo.solo.io
type Install struct {
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by gloo during validation
	Status core.Status `protobuf:"bytes,1,opt,name=status" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata             core.Metadata  `protobuf:"bytes,2,opt,name=metadata" json:"metadata"`
	Consul               *ConsulInstall `protobuf:"bytes,4,opt,name=consul" json:"consul,omitempty"`
	Encryption           *Encryption    `protobuf:"bytes,5,opt,name=encryption" json:"encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Install) Reset()         { *m = Install{} }
func (m *Install) String() string { return proto.CompactTextString(m) }
func (*Install) ProtoMessage()    {}
func (*Install) Descriptor() ([]byte, []int) {
	return fileDescriptor_install_57c18a0eb554c83e, []int{0}
}
func (m *Install) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install.Unmarshal(m, b)
}
func (m *Install) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install.Marshal(b, m, deterministic)
}
func (dst *Install) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install.Merge(dst, src)
}
func (m *Install) XXX_Size() int {
	return xxx_messageInfo_Install.Size(m)
}
func (m *Install) XXX_DiscardUnknown() {
	xxx_messageInfo_Install.DiscardUnknown(m)
}

var xxx_messageInfo_Install proto.InternalMessageInfo

func (m *Install) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Install) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Install) GetConsul() *ConsulInstall {
	if m != nil {
		return m.Consul
	}
	return nil
}

func (m *Install) GetEncryption() *Encryption {
	if m != nil {
		return m.Encryption
	}
	return nil
}

type ConsulInstall struct {
	// This is a path to the helm chart. This can be any path that the helm CLI would accept, including
	// local filesystem paths to archives or directories, or a URL to the archive
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsulInstall) Reset()         { *m = ConsulInstall{} }
func (m *ConsulInstall) String() string { return proto.CompactTextString(m) }
func (*ConsulInstall) ProtoMessage()    {}
func (*ConsulInstall) Descriptor() ([]byte, []int) {
	return fileDescriptor_install_57c18a0eb554c83e, []int{1}
}
func (m *ConsulInstall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsulInstall.Unmarshal(m, b)
}
func (m *ConsulInstall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsulInstall.Marshal(b, m, deterministic)
}
func (dst *ConsulInstall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsulInstall.Merge(dst, src)
}
func (m *ConsulInstall) XXX_Size() int {
	return xxx_messageInfo_ConsulInstall.Size(m)
}
func (m *ConsulInstall) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsulInstall.DiscardUnknown(m)
}

var xxx_messageInfo_ConsulInstall proto.InternalMessageInfo

func (m *ConsulInstall) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ConsulInstall) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*Install)(nil), "supergloo.solo.io.Install")
	proto.RegisterType((*ConsulInstall)(nil), "supergloo.solo.io.ConsulInstall")
}
func (this *Install) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Install)
	if !ok {
		that2, ok := that.(Install)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Consul.Equal(that1.Consul) {
		return false
	}
	if !this.Encryption.Equal(that1.Encryption) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ConsulInstall) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ConsulInstall)
	if !ok {
		that2, ok := that.(ConsulInstall)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Path != that1.Path {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("install.proto", fileDescriptor_install_57c18a0eb554c83e) }

var fileDescriptor_install_57c18a0eb554c83e = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x85, 0x20, 0x4a, 0x0d, 0x89, 0x34, 0xc4, 0xac, 0x44, 0x85, 0xec, 0x45, 0x2f, 0xb4,
	0x41, 0x2f, 0xc4, 0xc4, 0x83, 0x18, 0x63, 0x3c, 0x78, 0x59, 0x6f, 0xde, 0xca, 0x52, 0x96, 0x86,
	0xa5, 0xd3, 0x6c, 0x67, 0x4d, 0x7c, 0x00, 0xdf, 0xc5, 0x47, 0xf1, 0x29, 0x38, 0xf8, 0x08, 0x3e,
	0x81, 0xa1, 0x5b, 0x40, 0x22, 0x07, 0x4f, 0x6d, 0x66, 0xfe, 0xef, 0xcf, 0x3f, 0x33, 0xa4, 0xae,
	0xb4, 0x45, 0x91, 0xa6, 0xcc, 0x64, 0x80, 0x40, 0x1b, 0x36, 0x37, 0x32, 0x4b, 0x52, 0x00, 0x66,
	0x21, 0x05, 0xa6, 0xa0, 0xd5, 0x4c, 0x20, 0x01, 0xd7, 0xe5, 0x8b, 0x5f, 0x21, 0x6c, 0xf5, 0x12,
	0x85, 0x93, 0x7c, 0xc8, 0x62, 0x98, 0xf1, 0x85, 0xb2, 0xab, 0xa0, 0x78, 0xa7, 0x0a, 0xb9, 0x30,
	0x8a, 0xbf, 0xf6, 0xf8, 0x4c, 0xa2, 0x18, 0x09, 0x14, 0x1e, 0xe1, 0xff, 0x40, 0x2c, 0x0a, 0xcc,
	0xad, 0x07, 0x0e, 0xa5, 0x8e, 0xb3, 0x37, 0x83, 0x0a, 0x74, 0x51, 0x09, 0xdf, 0xcb, 0x64, 0xef,
	0xb1, 0x08, 0x4c, 0x1f, 0x48, 0xb5, 0x50, 0x07, 0xa5, 0x4e, 0xe9, 0xe2, 0xe0, 0xb2, 0xc9, 0x62,
	0xc8, 0xe4, 0x32, 0x36, 0x7b, 0x76, 0xbd, 0xc1, 0xf1, 0xe7, 0xbc, 0xbd, 0xf3, 0x3d, 0x6f, 0x37,
	0x50, 0x5a, 0x1c, 0xa9, 0xf1, 0xf8, 0x3a, 0x54, 0x89, 0x86, 0x4c, 0x86, 0x91, 0xc7, 0x69, 0x9f,
	0xec, 0x2f, 0x93, 0x06, 0x65, 0x67, 0x75, 0xb4, 0x69, 0xf5, 0xe4, 0xbb, 0x83, 0xca, 0xc2, 0x2c,
	0x5a, 0xa9, 0x69, 0x9f, 0x54, 0x63, 0xd0, 0x36, 0x4f, 0x83, 0x8a, 0xe3, 0x3a, 0xec, 0xcf, 0xfa,
	0xd8, 0x9d, 0x13, 0xf8, 0xd0, 0x91, 0xd7, 0xd3, 0x1b, 0x42, 0xd6, 0xc3, 0x05, 0xbb, 0x8e, 0x3e,
	0xdd, 0x42, 0xdf, 0xaf, 0x44, 0xd1, 0x2f, 0x20, 0xbc, 0x25, 0xf5, 0x0d, 0x5f, 0x4a, 0x49, 0xc5,
	0x08, 0x9c, 0xb8, 0x55, 0xd4, 0x22, 0xf7, 0xa7, 0x27, 0xa4, 0xa6, 0xc5, 0x4c, 0x5a, 0x23, 0x62,
	0xe9, 0x06, 0xab, 0x45, 0xeb, 0xc2, 0xa0, 0xfb, 0xf1, 0x75, 0x56, 0x7a, 0x39, 0xdf, 0x76, 0x93,
	0x65, 0x0a, 0x6e, 0xa6, 0x89, 0x3f, 0xcc, 0xb0, 0xea, 0x0e, 0x70, 0xf5, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x34, 0xae, 0x31, 0x30, 0x02, 0x00, 0x00,
}
