// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: observability.proto

package v1 // import "github.com/solo-io/supergloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
import _ "github.com/solo-io/supergloo/pkg/api/external/gloo/v1"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// observability config for the mesh
type Observability struct {
	// mesh configuration for prometheus
	Prometheus           *Prometheus `protobuf:"bytes,1,opt,name=prometheus" json:"prometheus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Observability) Reset()         { *m = Observability{} }
func (m *Observability) String() string { return proto.CompactTextString(m) }
func (*Observability) ProtoMessage()    {}
func (*Observability) Descriptor() ([]byte, []int) {
	return fileDescriptor_observability_fec65dee72c8f51d, []int{0}
}
func (m *Observability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observability.Unmarshal(m, b)
}
func (m *Observability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observability.Marshal(b, m, deterministic)
}
func (dst *Observability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observability.Merge(dst, src)
}
func (m *Observability) XXX_Size() int {
	return xxx_messageInfo_Observability.Size(m)
}
func (m *Observability) XXX_DiscardUnknown() {
	xxx_messageInfo_Observability.DiscardUnknown(m)
}

var xxx_messageInfo_Observability proto.InternalMessageInfo

func (m *Observability) GetPrometheus() *Prometheus {
	if m != nil {
		return m.Prometheus
	}
	return nil
}

//
type Prometheus struct {
	PrometheusConfigMap  *core.ResourceRef `protobuf:"bytes,1,opt,name=prometheus_config_map,json=prometheusConfigMap" json:"prometheus_config_map,omitempty"`
	EnableMetrics        bool              `protobuf:"varint,3,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Prometheus) Reset()         { *m = Prometheus{} }
func (m *Prometheus) String() string { return proto.CompactTextString(m) }
func (*Prometheus) ProtoMessage()    {}
func (*Prometheus) Descriptor() ([]byte, []int) {
	return fileDescriptor_observability_fec65dee72c8f51d, []int{1}
}
func (m *Prometheus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prometheus.Unmarshal(m, b)
}
func (m *Prometheus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prometheus.Marshal(b, m, deterministic)
}
func (dst *Prometheus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prometheus.Merge(dst, src)
}
func (m *Prometheus) XXX_Size() int {
	return xxx_messageInfo_Prometheus.Size(m)
}
func (m *Prometheus) XXX_DiscardUnknown() {
	xxx_messageInfo_Prometheus.DiscardUnknown(m)
}

var xxx_messageInfo_Prometheus proto.InternalMessageInfo

func (m *Prometheus) GetPrometheusConfigMap() *core.ResourceRef {
	if m != nil {
		return m.PrometheusConfigMap
	}
	return nil
}

func (m *Prometheus) GetEnableMetrics() bool {
	if m != nil {
		return m.EnableMetrics
	}
	return false
}

func init() {
	proto.RegisterType((*Observability)(nil), "supergloo.solo.io.Observability")
	proto.RegisterType((*Prometheus)(nil), "supergloo.solo.io.Prometheus")
}
func (this *Observability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Observability)
	if !ok {
		that2, ok := that.(Observability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Prometheus.Equal(that1.Prometheus) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Prometheus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Prometheus)
	if !ok {
		that2, ok := that.(Prometheus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PrometheusConfigMap.Equal(that1.PrometheusConfigMap) {
		return false
	}
	if this.EnableMetrics != that1.EnableMetrics {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("observability.proto", fileDescriptor_observability_fec65dee72c8f51d) }

var fileDescriptor_observability_fec65dee72c8f51d = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x08, 0x22, 0x2b, 0x15, 0x4c, 0x14, 0x6a, 0xc0, 0x52, 0x0a, 0x62, 0x0f, 0x76, 0x17,
	0xf5, 0xec, 0x45, 0xcf, 0x51, 0xc9, 0xd1, 0x4b, 0xd8, 0x8d, 0x2f, 0xdb, 0xa5, 0x49, 0xde, 0xb2,
	0x1f, 0x55, 0xaf, 0xfe, 0x1a, 0x7f, 0x97, 0xbf, 0x44, 0xf2, 0x61, 0x53, 0xd0, 0x9e, 0x76, 0xdf,
	0x9b, 0x99, 0x37, 0xcc, 0x90, 0x08, 0x85, 0x05, 0xb3, 0xe6, 0x42, 0x95, 0xca, 0x7d, 0x50, 0x6d,
	0xd0, 0x61, 0x78, 0x6c, 0xbd, 0x06, 0x23, 0x4b, 0x44, 0x6a, 0xb1, 0x44, 0xaa, 0x30, 0x3e, 0x91,
	0x28, 0xb1, 0x45, 0x59, 0xf3, 0xeb, 0x88, 0xf1, 0x44, 0x22, 0xca, 0x12, 0x58, 0x3b, 0x09, 0x5f,
	0xb0, 0x57, 0x6f, 0xb8, 0x53, 0x58, 0xef, 0xc2, 0xdf, 0x0c, 0xd7, 0x1a, 0x8c, 0xed, 0xf1, 0xa8,
	0xf1, 0x60, 0xeb, 0xeb, 0x86, 0xf0, 0xde, 0xbb, 0xc7, 0x57, 0x52, 0xb9, 0xa5, 0x17, 0x34, 0xc7,
	0x8a, 0x35, 0xf6, 0x0b, 0x85, 0xdd, 0xbb, 0x52, 0x8e, 0x71, 0xad, 0x1a, 0xbe, 0x81, 0xa2, 0x63,
	0xcf, 0x1e, 0xc9, 0xe8, 0x69, 0x3b, 0x42, 0x78, 0x47, 0x88, 0x36, 0x58, 0x81, 0x5b, 0x82, 0xb7,
	0xe3, 0x60, 0x1a, 0xcc, 0x0f, 0x6f, 0xce, 0xe9, 0x9f, 0x44, 0xf4, 0x79, 0x43, 0x4a, 0xb7, 0x04,
	0xb3, 0xcf, 0x80, 0x90, 0x01, 0x0a, 0x13, 0x72, 0x3a, 0x80, 0x59, 0x8e, 0x75, 0xa1, 0x64, 0x56,
	0x71, 0xdd, 0x1f, 0x3e, 0xa3, 0x39, 0x1a, 0xd8, 0xdc, 0x4c, 0xc1, 0xa2, 0x37, 0x39, 0xa4, 0x50,
	0xa4, 0xd1, 0xa0, 0x7b, 0x68, 0x65, 0x09, 0xd7, 0xe1, 0x05, 0x39, 0x82, 0x9a, 0x8b, 0x12, 0xb2,
	0x0a, 0x9c, 0x51, 0xb9, 0x1d, 0xef, 0x4d, 0x83, 0xf9, 0x41, 0x3a, 0xea, 0xb6, 0x49, 0xb7, 0xbc,
	0x5f, 0x7c, 0x7d, 0x4f, 0x82, 0x97, 0xcb, 0xff, 0x8a, 0xf8, 0xcd, 0xc1, 0xf4, 0x4a, 0xf6, 0x6d,
	0x88, 0xfd, 0xb6, 0x8a, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x66, 0x4b, 0x1b, 0xcd,
	0x01, 0x00, 0x00,
}
