// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: policy.proto

package v1 // import "github.com/solo-io/supergloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Policy struct {
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_f5cbd493936bdad4, []int{0}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type Rule struct {
	Source               *core.ResourceRef `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Destination          *core.ResourceRef `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_f5cbd493936bdad4, []int{1}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetSource() *core.ResourceRef {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Rule) GetDestination() *core.ResourceRef {
	if m != nil {
		return m.Destination
	}
	return nil
}

func init() {
	proto.RegisterType((*Policy)(nil), "supergloo.solo.io.Policy")
	proto.RegisterType((*Rule)(nil), "supergloo.solo.io.Rule")
}
func (this *Policy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Policy)
	if !ok {
		that2, ok := that.(Policy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Rules) != len(that1.Rules) {
		return false
	}
	for i := range this.Rules {
		if !this.Rules[i].Equal(that1.Rules[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Rule) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Rule)
	if !ok {
		that2, ok := that.(Rule)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Source.Equal(that1.Source) {
		return false
	}
	if !this.Destination.Equal(that1.Destination) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_policy_f5cbd493936bdad4) }

var fileDescriptor_policy_f5cbd493936bdad4 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0xcf, 0xc9,
	0x4c, 0xae, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0x2e, 0x2d, 0x48, 0x2d, 0x4a,
	0xcf, 0xc9, 0xcf, 0xd7, 0x2b, 0xce, 0xcf, 0xc9, 0xd7, 0xcb, 0xcc, 0x97, 0x12, 0x49, 0xcf, 0x4f,
	0xcf, 0x07, 0xcb, 0xea, 0x83, 0x58, 0x10, 0x85, 0x52, 0x3a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49,
	0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x20, 0x95, 0xba, 0x99, 0xf9, 0x10, 0x3a, 0x3b, 0xb3, 0x44, 0x3f,
	0xb1, 0x20, 0x53, 0xbf, 0xcc, 0x50, 0xbf, 0x28, 0x35, 0x0d, 0xa2, 0x5a, 0xc9, 0x9c, 0x8b, 0x2d,
	0x00, 0x6c, 0x8d, 0x90, 0x2e, 0x17, 0x6b, 0x51, 0x69, 0x4e, 0x6a, 0xb1, 0x04, 0x93, 0x02, 0xb3,
	0x06, 0xb7, 0x91, 0xb8, 0x1e, 0x86, 0x85, 0x7a, 0x41, 0xa5, 0x39, 0xa9, 0x41, 0x10, 0x55, 0x4a,
	0x65, 0x5c, 0x2c, 0x20, 0xae, 0x90, 0x21, 0x17, 0x5b, 0x71, 0x7e, 0x69, 0x51, 0x72, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa4, 0x5e, 0x72, 0x7e, 0x51, 0x2a, 0x42, 0x4b, 0x2a, 0x44,
	0x36, 0x28, 0x35, 0x2d, 0x08, 0xaa, 0x50, 0xc8, 0x9a, 0x8b, 0x3b, 0x25, 0xb5, 0xb8, 0x24, 0x33,
	0x2f, 0xb1, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x89, 0x90, 0x3e, 0x64, 0xd5, 0x4e, 0xba, 0x2b, 0x1e,
	0xc9, 0x31, 0x46, 0xa9, 0x63, 0xf3, 0x24, 0xcc, 0xbd, 0xfa, 0x05, 0xd9, 0xe9, 0x50, 0x9f, 0x26,
	0xb1, 0x81, 0xbd, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x66, 0x8c, 0xf7, 0x02, 0x4d, 0x01,
	0x00, 0x00,
}
