// Code generated by protoc-gen-solo-kit. DO NOT EDIT.

package v1

import (
	"sort"

	"github.com/gogo/protobuf/proto"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/kube/crd"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
	"github.com/solo-io/solo-kit/pkg/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// TODO: modify as needed to populate additional fields
func NewRoutingRule(namespace, name string) *RoutingRule {
	return &RoutingRule{
		Metadata: core.Metadata{
			Name:      name,
			Namespace: namespace,
		},
	}
}

func (r *RoutingRule) SetStatus(status core.Status) {
	r.Status = status
}

func (r *RoutingRule) SetMetadata(meta core.Metadata) {
	r.Metadata = meta
}

type RoutingRuleList []*RoutingRule
type RoutingrulesByNamespace map[string]RoutingRuleList

// namespace is optional, if left empty, names can collide if the list contains more than one with the same name
func (list RoutingRuleList) Find(namespace, name string) (*RoutingRule, error) {
	for _, routingRule := range list {
		if routingRule.Metadata.Name == name {
			if namespace == "" || routingRule.Metadata.Namespace == namespace {
				return routingRule, nil
			}
		}
	}
	return nil, errors.Errorf("list did not find routingRule %v.%v", namespace, name)
}

func (list RoutingRuleList) AsResources() resources.ResourceList {
	var ress resources.ResourceList
	for _, routingRule := range list {
		ress = append(ress, routingRule)
	}
	return ress
}

func (list RoutingRuleList) AsInputResources() resources.InputResourceList {
	var ress resources.InputResourceList
	for _, routingRule := range list {
		ress = append(ress, routingRule)
	}
	return ress
}

func (list RoutingRuleList) Names() []string {
	var names []string
	for _, routingRule := range list {
		names = append(names, routingRule.Metadata.Name)
	}
	return names
}

func (list RoutingRuleList) NamespacesDotNames() []string {
	var names []string
	for _, routingRule := range list {
		names = append(names, routingRule.Metadata.Namespace+"."+routingRule.Metadata.Name)
	}
	return names
}

func (list RoutingRuleList) Sort() RoutingRuleList {
	sort.SliceStable(list, func(i, j int) bool {
		return list[i].Metadata.Less(list[j].Metadata)
	})
	return list
}

func (list RoutingRuleList) Clone() RoutingRuleList {
	var routingRuleList RoutingRuleList
	for _, routingRule := range list {
		routingRuleList = append(routingRuleList, proto.Clone(routingRule).(*RoutingRule))
	}
	return routingRuleList
}

func (list RoutingRuleList) ByNamespace() RoutingrulesByNamespace {
	byNamespace := make(RoutingrulesByNamespace)
	for _, routingRule := range list {
		byNamespace.Add(routingRule)
	}
	return byNamespace
}

func (byNamespace RoutingrulesByNamespace) Add(routingRule ...*RoutingRule) {
	for _, item := range routingRule {
		byNamespace[item.Metadata.Namespace] = append(byNamespace[item.Metadata.Namespace], item)
	}
}

func (byNamespace RoutingrulesByNamespace) Clear(namespace string) {
	delete(byNamespace, namespace)
}

func (byNamespace RoutingrulesByNamespace) List() RoutingRuleList {
	var list RoutingRuleList
	for _, routingRuleList := range byNamespace {
		list = append(list, routingRuleList...)
	}
	return list.Sort()
}

func (byNamespace RoutingrulesByNamespace) Clone() RoutingrulesByNamespace {
	return byNamespace.List().Clone().ByNamespace()
}

var _ resources.Resource = &RoutingRule{}

// Kubernetes Adapter for RoutingRule

func (o *RoutingRule) GetObjectKind() schema.ObjectKind {
	t := RoutingRuleCrd.TypeMeta()
	return &t
}

func (o *RoutingRule) DeepCopyObject() runtime.Object {
	return resources.Clone(o).(*RoutingRule)
}

var RoutingRuleCrd = crd.NewCrd("supergloo.solo.io",
	"routingrules",
	"supergloo.solo.io",
	"v1",
	"RoutingRule",
	"rr",
	&RoutingRule{})
